btotharye/mycroft-homeassistant

- __init__.py
- regex/en-us/sensor.rx
- vocab/en-us/SensorStatusKeyword.voc
> Sensor intent

- README.md
- __init__.py
- dialog/en-us/homeassistant.automation.trigger.dialog
- regex/en-us/action.rx
- regex/en-us/automation.rx
- vocab/en-us/AutomationActionKeyword.voc
adding in ability to activate automations
> Automation add

- vocab/de/SensorStatusKeyword.voc
i did a misleading sensorkeyword, which censors for example the german weatherskill. this fixes it. :)
> avoid (german) conflicts with other skills

- regex/de/sensor.rx
really forgott this commit to pr.. my last pr makes no sense with this change (allow "was ist" on other places as well).
> finish previous conflicts

- README.md
> Updated README with python-dev requirement

- README.md
- __init__.py
- dialog/de/homeassistant.tracker.found.dialog
- dialog/en-us/homeassistant.tracker.found.dialog
- regex/en-us/sensor.rx
- regex/en-us/tracker.rx
- vocab/en-us/DeviceTrackerKeyword.voc
- vocab/en-us/LightActionKeyword.voc
- vocab/en-us/SensorStatusKeyword.voc
> Device Tracker, plus QOL fixes for default ports and SSL verify to allow disable if user chooses.

- README.md
- __init__.py
- dialog/en-us/homeassistant.automation.trigger.dialog
- dialog/en-us/homeassistant.brightness.badreq.dialog
- dialog/en-us/homeassistant.device.already.dialog
- dialog/en-us/homeassistant.device.off.dialog
- dialog/en-us/homeassistant.device.on.dialog
- dialog/en-us/homeassistant.device.toggle.dialog
- dialog/en-us/homeassistant.device.unknown.dialog
- regex/en-us/automation.rx
- regex/en-us/sensor.rx
- regex/en-us/switch.rx
- vocab/en-us/AutomationActionKeyword.voc
- vocab/en-us/LightsKeyword.voc
- vocab/en-us/SensorStatusKeyword.voc
Adds keywords and regular expressions for increased everyday usability (and additional dialog lines for additional fun!)
Also implements sensor readings, scene and script activating and light toggleing.
> Increased usability through more keywords and regular expressions

- __init__.py
- dialog/en-us/homeassistant.sensor.dialog
- regex/en-us/sensor.rx
- regex/en-us/switch.rx
> Increased usability with better entity matching, more dialogs and unit extraction

- __init__.py
- dialog/en-us/homeassistant.device.unknown.dialog
- dialog/en-us/homeassistant.error.offline.dialog
- dialog/en-us/homeassistant.error.setup.dialog
- settingsmeta.json
Changed some lines so that home assistant will work without a config at all. Also will ignore manual configuration in the future
TODO somehow sets verify to true very often
Also amended some dialoge options for more pleasure for your ears
> Updated the system to work through settingsmeta alone

- __init__.py
This allows me to say "turn on bedroom fan"/"turn off bedroom fan"
> Allow fans to be switched on/off

- __init__.py
- settingsmeta.json
**Related issue (if applicable):** fixes #30
> Set default value for port number and except parsing errors

- README.md
**Related issue (if applicable):** fixes request by @btotharye: https://github.com/btotharye/mycroft-homeassistant/commit/f58b9bdb321f9647a6f65621cb3a4e5435ded539#commitcomment-29285157
> Update Readme.md about conversation fallback

- README.md
> Testing Jenkins

- .travis.yml
- unittests/test_haclient.py
> updating coverage tests

- ha_client.py
Updating the skill to work if the user isn't using a port IE has a proxy setup, etc.
> updating url to work if port is empty

- .coveragerc
- unittests/test_haclient.py
> Testing climate stuff

- __init__.py
This is tested on my local PiCroft, latest image, and confirmed to work.
**Related issue (if applicable):** fixes #54
> Force refresh of HAClient on websettings change

- __init__.py
- dialog/en-us/homeassistant.error.dialog
- dialog/en-us/homeassistant.error.http.dialog
- dialog/en-us/homeassistant.error.invalidurl.dialog
- dialog/en-us/homeassistant.error.ssl.dialog
- dialog/en-us/homeassistant.error.wrong_password.dialog
- ha_client.py
The HAClient object does not catch errors anymore, so that home assistant itself can provide error handling advices.
> Valuable error messages

- __init__.py
Uses the builtin nice_number method to convert sensor values to human readable values. Also includes  switches for sensor readings (their state may as well be interesting)
> Nice format for numeric values

- __init__.py
Found a small bug :)
Fixed a small bug that made login to HA not posible whith ssl
#62 #65
> Fix login error

- __init__.py
**Related issue (if applicable):** fixes #80 and possibly #72
> Fixed configuration changing to default

- __init__.py
Uses the new "nice_unit" method in mycroft utils for pronouncing the units from home-assistant.
The according pull request at mycroft-core has yet to be approved
> WIP: Use new nice_unit instead of old malfunctioning quantulum

- __init__.py
Reverts btotharye/mycroft-homeassistant#78
> Revert "WIP: Use new nice_unit instead of old malfunctioning quantulum"
